 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_caption
  backbone_arch: vit

  load_finetuned: False
  pretrained: "modelzoo/BLIP/model_large.pth"

  # vit encoder
  vit_type: "large"
  vit_grad_ckpt: True
  vit_ckpt_layer: 5

  image_size: 384

  # bert config
  med_config_path: "configs/models/med_large_config.json"

  # generation configs
  prompt: "a picture of "


preprocess:
    vis_processor:
        train:
          name: "blip_post_video_train"
        eval:
          name: "blip_post_video_eval"
    text_processor:
        train:
          name: "blip_caption"
          prompt: "a picture of "
        eval:
          name: "blip_caption"
