 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_qa
  model_type: base
  vit_grad_ckpt: True
  vit_ckpt_layer: 4
  
  image_size: 384
  num_frames: 16
  load_finetuned: False
  adapter_configs:
    arch: blip_post_concat_adapter

datasets:
  msrvtt_qa: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_post_video_train"
          n_frms: 16
          image_size: 384
        eval:
          name: "blip_post_video_eval"
          n_frms: 16
          image_size: 384
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_qa/qa_train.json
        val:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_qa/qa_val.json
        test:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_qa/qa_test.json
      videos:
        storage: data/MultimodalDataset/msrvtt/vis_db/msrvtt

run:
  task: gqa
  max_len: 5
  min_len: 1
  num_beams: 3
  inference_method: 'generate'

  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  warmup_lr: 2e-6
  warmup_steps: 1000
  init_lr: 2e-5 # for global bs 128
  min_lr: 2e-6
  weight_decay: 0.04
  max_epoch: 10

  # dataloading
  num_workers: 8
  batch_size_train: 4
  batch_size_eval: 8

  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution training
  amp: True
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False

  # misc
  seed: 42
  log_freq: 10
  resume_ckpt_path: null
  output_dir: "output/blip_concat_f16_384_amp/msrvtt_qa_2e-5_b32_ft"