 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_mc_qa
  model_type: base
  vit_grad_ckpt: True
  vit_ckpt_layer: 5

  backbone_arch: timesformer
  layers_w_divst: [8, 9, 10, 11]
  load_finetuned: False
  
  num_frames: 16
  image_size: 224
  num_classes: 5
  
  alpha: 0.4

datasets:
  nextqa: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_post_video_train"
          n_frms: 16
          image_size: 224
        eval:
          name: "blip_post_video_eval"
          n_frms: 16
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: data/MultimodalDataset/nextqa/txt_db/nextqa_mc/train.jsonl
        val:
          storage: data/MultimodalDataset/nextqa/txt_db/nextqa_mc/val.jsonl
        test:
          storage: data/MultimodalDataset/nextqa/txt_db/nextqa_mc/test.jsonl
      videos:
        storage: data/MultimodalDataset/nextqa/vis_db/nextqa

run:
  task: multimodal_classification
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  warmup_lr: 2e-7
  warmup_steps: 500
  init_lr: 2e-6 # for global bs 128
  min_lr: 0
  weight_decay: 0.04
  max_epoch: 6

  # dataloading
  num_workers: 8
  batch_size_train: 8
  batch_size_eval: 32

  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution training
  amp: True
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False

  # misc
  seed: 42
  log_freq: 10
  resume_ckpt_path: null
  output_dir: "output/blip_divst_8to11_f16_224/nextqa_2e-6_b64_ft"