 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_mc_qa
  model_type: base
  backbone_arch: center_clip
  vit_grad_ckpt: True
  vit_ckpt_layer: 4
  
  image_size: 224
  num_classes: 5
  load_finetuned: False
  alpha: 0.4
  
  cluster_cfg:
    num_frames: 16
    cluster_algo: 'kmediods++'
    cluster_threshold: 1e-6
    cluster_distance: 'euclidean'
    minkowski_norm_p: 2.0
    cluster_iter_limit: 100
    cluster_inter: 1
    pretrained_clip_name: 'ViT-B/16'
    cluster_embedding: 0
    cluster_frame_embedding: 0
    cluster_num_blocks: [196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196]
    target_frames_blocks: [16, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8]
    deep_cluster: 0
    spectral_knn_k: 1
    spectral_sigma: 2.0
    spectral_graph: 'HeatKernel'

datasets:
  nextqa: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_post_video_train"
          n_frms: 16
          image_size: 224
        eval:
          name: "blip_post_video_eval"
          n_frms: 16
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: data/MultimodalDataset/nextqa/txt_db/nextqa_mc/train.jsonl
        val:
          storage: data/MultimodalDataset/nextqa/txt_db/nextqa_mc/val.jsonl
        test:
          storage: data/MultimodalDataset/nextqa/txt_db/nextqa_mc/test.jsonl
      videos:
        storage: data/MultimodalDataset/nextqa/vis_db/nextqa

run:
  task: multimodal_classification
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  warmup_lr: 1e-6
  warmup_steps: 500
  init_lr: 1e-5
  min_lr: 0
  weight_decay: 0.04
  max_epoch: 6

  # dataloading
  num_workers: 8
  batch_size_train: 8
  batch_size_eval: 32

  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution training
  amp: True
  device: "cuda"
  world_size: 16
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False

  # misc
  seed: 42
  log_freq: 10
  resume_ckpt_path: null
  output_dir: "output/blip_centerclip_f16to8_layer7_224_amp/nextqa_1e-5_b64_ft"