 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_retrieval
  model_type: msrvtt
  backbone_arch: center_clip
  load_finetuned: False
  
  image_size: 224
  
  cluster_cfg:
    num_frames: 32
    cluster_algo: 'kmediods++'
    cluster_threshold: 1e-6
    cluster_distance: 'euclidean'
    minkowski_norm_p: 2.0
    cluster_iter_limit: 100
    cluster_inter: 1
    pretrained_clip_name: 'ViT-B/16'
    cluster_embedding: 0
    cluster_frame_embedding: 0
    cluster_num_blocks: [196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196, 196]
    target_frames_blocks: [32, 32, 32, 32, 32, 32, 32, 16, 16, 16, 16, 16]
    deep_cluster: 0
    spectral_knn_k: 1
    spectral_sigma: 2.0
    spectral_graph: 'HeatKernel'
  
  queue_size: 57600
  alpha: 0.4
  negative_all_rank: True

datasets:
  msrvtt_retrieval: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_post_video_train"
          n_frms: 32
          image_size: 224
        eval:
          name: "blip_post_video_eval"
          n_frms: 32
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: data/MultimodalDataset/anet/txt_db/anet_retrieval/train.jsonl
        val:
          storage: data/MultimodalDataset/anet/txt_db/anet_retrieval/dev.jsonl
        test:
          storage: data/MultimodalDataset/anet/txt_db/anet_retrieval/val1.jsonl
      videos:
        storage: data/MultimodalDataset/anet/vis_db/anet

run:
  task: retrieval
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  warmup_lr: 2e-6
  warmup_steps: 500
  init_lr: 2e-5
  min_lr: 2e-6
  weight_decay: 0.04
  max_epoch: 10

  # dataloading
  num_workers: 8
  batch_size_train: 8
  batch_size_eval: 16

  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # model specific
  k_test: 128

  # distribution training
  amp: True
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False

  # misc
  seed: 42
  log_freq: 10
  resume_ckpt_path: null
  output_dir: "output/anet_retrieval/blip_centerclip/f32to16_layer7_224_amp_global_neg_top128_2e-5_b128_e10_ft_node"