 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_retrieval
  model_type: msrvtt
  backbone_arch: timesformer
  load_finetuned: True
  finetuned: "output/BLIP/model_base_retrieval_coco.pth"
  num_frames: 1

datasets:
  msrvtt_retrieval: # name of the dataset builder
    vis_processor:
        eval:
          name: "blip_post_video_eval"
          n_frms: 1
          image_size: 384
    text_processor:
        eval:
          name: "blip_caption"
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_retrieval/train_1kA.jsonl
        val:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_retrieval/test.jsonl
        test:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_retrieval/test.jsonl
      videos:
        storage: data/MultimodalDataset/msrvtt/vis_db/msrvtt

run:
  task: retrieval
  # optimization-specific
  batch_size_train: 16
  batch_size_eval: 32
  num_workers: 4

  # k_test: 128
  k_test: 10 # FIXME

  seed: 42
  output_dir: "output/blip_divst_8f_top128_coco/msrvtt_retrieval_zeroshot"

  evaluate: True
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False
