 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip_video_post_caption
  model_type: msrvtt
  backbone_arch: timesformer
  load_finetuned: False

  num_frames: 8
  image_size: 224
  
  prompt: "What does the video describe?"

datasets:
  msrvtt_caption: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_post_video_train"
          n_frms: 8
          image_size: 224
        eval:
          name: "blip_post_video_eval"
          n_frms: 8
          image_size: 224
    text_processor:
        train:
          name: "blip_caption"
          prompt: ""
        eval:
          name: "blip_caption"
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_caption/train.jsonl
        val:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_caption/test.jsonl
        test:
          storage: data/MultimodalDataset/msrvtt/txt_db/msrvtt_caption/test.jsonl
      videos:
        storage: data/MultimodalDataset/msrvtt/vis_db/msrvtt

run:
  task: captioning
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  warmup_lr: 5e-7
  warmup_steps: 500
  init_lr: 5e-6 # for global bs 128
  min_lr: 0
  weight_decay: 0.04
  max_epoch: 10

  # dataloading
  num_workers: 8
  batch_size_train: 16
  batch_size_eval: 32

  # decoding options
  max_len: 32
  min_len: 5
  num_beams: 3

  train_splits: ["train"]
  valid_splits: ["test"]
  test_splits: ["test"]

  # distribution-specific
  amp: False
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False

  # misc
  seed: 42
  log_freq: 10
  resume_ckpt_path: null
  output_dir: "output/blip_divst_8f_224/msrvtt_caption_lr5e-6_b128_ft"